### ISSUE TITLE
Task: rewrite the footer with bootstrap in v2 (1pt) 

### ISSUE THREAD

**Issue by stacysealky** [donategifts/donategifts-frontend#59]
After the tailwind to bootstrap migration, the styling of the footer broke. 
Please rewrite the footer to match v1 design 
<img width="1786" alt="Screen Shot 2022-09-15 at 8 54 59 PM" src="https://user-images.githubusercontent.com/26069780/190553417-a8a37fa3-56ae-4ce1-b9cd-6a79e112982b.png">

Current v2: 
<img width="1784" alt="Screen Shot 2022-09-15 at 8 55 09 PM" src="https://user-images.githubusercontent.com/26069780/190553441-839a8c15-ffd3-4215-b10f-c3e48931b0dc.png">

**Comment by Enubia** [comment]
https://github.com/donategifts/donategifts-frontend/pull/66
